### ISSUE TITLE
A problem when running the code

### ISSUE THREAD

**Issue by wangze09** [mhlee216/MGCVAE#1]
Dear Lee,
When I ran the code, I met the problem as follows. I tried to solve the problem but failed since I was not very familiar with molecular generation. Could you tell me how to solve that problem when you are free? Thanks a lot.

Converting to graphs...
Traceback (most recent call last):
  File "mgcvae.py", line 186, in <module>
    feature_size(data[i], atom_labels, atom_number), 
  File "/home/MGCVAE/code/graph_converter.py", line 14, in feature_size
    feature = torch.cat([torch.tensor(feature), torch.zeros(atom_number-feature.shape[0], feature.shape[1])], 0)
RuntimeError: Expected object of scalar type double but got scalar type float for sequence element 1.

Yours sincerely ze

**Comment by mhlee216** [comment]
Sorry. That's my mistake.
Please try again with this:

`def feature_size(mol, atom_labels, max_length=None): 
    feature = graph_features(mol, atom_labels, max_length=None)
    feature = torch.cat([torch.tensor(feature), torch.zeros([atom_number-feature.shape[0], feature.shape[1]])], 0)
    for i in range(feature.shape[0]):
        if 1 not in feature[i]:
            feature[i, 0] = 1
    return feature`

Good luck!

**Comment by wangze09** [comment]
> Sorry. That's my mistake. Please try again with this:
> 
> ```
> def feature_size(mol, atom_labels, max_length=None): 
>     feature = graph_features(mol, atom_labels, max_length=None)
>     feature = torch.cat([torch.tensor(feature), torch.zeros([atom_number-feature.shape[0], feature.shape[1]])], 0)
>     for i in range(feature.shape[0]):
>         if 1 not in feature[i]:
>             feature[i, 0] = 1
>     return feature
> ```
> 
> Good luck!

Thanks a lot Lee!
But something went wrong as follows.

Converting to graphs...
Traceback (most recent call last):
  File "mgcvae.py", line 186, in <module>
    feature_size(data[i], atom_labels, atom_number), 
  File "/home/MGCVAE/code/graph_converter.py", line 22, in feature_size
    feature = torch.cat([torch.tensor(feature), torch.zeros([atom_number-feature.shape[0], feature.shape[1]])], 0)
NameError: name 'atom_number' is not defined

Thanks a lot for answering me!

**Comment by mhlee216** [comment]
Sorry.
There was a minor problem with integrating the MGVAE and MGCVAE codes into one.
Please try the below again:

```
def feature_size(mol, atom_labels, max_length=None): 
    feature = graph_features(mol, atom_labels, max_length)
    feature = torch.cat([torch.tensor(feature), torch.zeros([max_length-feature.shape[0], feature.shape[1]])], 0)
    for i in range(feature.shape[0]):
        if 1 not in feature[i]:
            feature[i, 0] = 1
    return feature
```

A simple test worked fine for me:

```
import torch
import numpy as np
import pandas as pd
from rdkit import Chem
from rdkit.Chem.Crippen import MolLogP, MolMR

def graph_features(mol, atom_labels, max_length=None):
    max_length = max_length if max_length is not None else mol.GetNumAtoms()
    features = np.array([[*[a.GetAtomicNum() == i for i in atom_labels]] for a in mol.GetAtoms()], dtype=np.int32)
    return np.vstack((features, np.zeros((max_length - features.shape[0], features.shape[1]))))

def feature_size(mol, atom_labels, max_length=None): 
    feature = graph_features(mol, atom_labels, max_length)
    feature = torch.cat([torch.tensor(feature), torch.zeros([max_length-feature.shape[0], feature.shape[1]])], 0)
    for i in range(feature.shape[0]):
        if 1 not in feature[i]:
            feature[i, 0] = 1
    return feature

mol = Chem.MolFromSmiles('CNCCCCCC')
data = [mol]
atom_labels = sorted(set([atom.GetAtomicNum() for mol in data for atom in mol.GetAtoms()] + [0]))
print(feature_size(data[0], atom_labels, 10))
```

```
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]], dtype=torch.float64)
```

Thank you.

**Comment by wangze09** [comment]
> Sorry. There was a minor problem with integrating the MGVAE and MGCVAE codes into one. Please try the below again:
> 
> ```
> def feature_size(mol, atom_labels, max_length=None): 
>     feature = graph_features(mol, atom_labels, max_length)
>     feature = torch.cat([torch.tensor(feature), torch.zeros([max_length-feature.shape[0], feature.shape[1]])], 0)
>     for i in range(feature.shape[0]):
>         if 1 not in feature[i]:
>             feature[i, 0] = 1
>     return feature
> ```
> 
> A simple test worked fine for me:
> 
> ```
> import torch
> import numpy as np
> import pandas as pd
> from rdkit import Chem
> from rdkit.Chem.Crippen import MolLogP, MolMR
> 
> def graph_features(mol, atom_labels, max_length=None):
>     max_length = max_length if max_length is not None else mol.GetNumAtoms()
>     features = np.array([[*[a.GetAtomicNum() == i for i in atom_labels]] for a in mol.GetAtoms()], dtype=np.int32)
>     return np.vstack((features, np.zeros((max_length - features.shape[0], features.shape[1]))))
> 
> def feature_size(mol, atom_labels, max_length=None): 
>     feature = graph_features(mol, atom_labels, max_length)
>     feature = torch.cat([torch.tensor(feature), torch.zeros([max_length-feature.shape[0], feature.shape[1]])], 0)
>     for i in range(feature.shape[0]):
>         if 1 not in feature[i]:
>             feature[i, 0] = 1
>     return feature
> 
> mol = Chem.MolFromSmiles('CNCCCCCC')
> data = [mol]
> atom_labels = sorted(set([atom.GetAtomicNum() for mol in data for atom in mol.GetAtoms()] + [0]))
> print(feature_size(data[0], atom_labels, 10))
> ```
> 
> ```
> tensor([[0., 1., 0.],
>         [0., 0., 1.],
>         [0., 1., 0.],
>         [0., 1., 0.],
>         [0., 1., 0.],
>         [0., 1., 0.],
>         [0., 1., 0.],
>         [0., 1., 0.],
>         [1., 0., 0.],
>         [1., 0., 0.]], dtype=torch.float64)
> ```
> 
> Thank you.

Thanks a lot Lee！
I successfully ran the whole project.
Have a nice day！
